DOCKER_TAG ?= latest
DOCKER_IMAGE ?= quay.io/linux-whitehat/diuid:$(DOCKER_TAG)

IMAGE_BASE_NAME ?= debian
IMAGE_BASE_VERSION ?= 12.4
KERNEL_VERSION ?= 6.6
GOLANG_VERSION ?= 1.17.6
DOCKER_CHANNEL ?= stable
DOCKER_VERSION ?= 5:24.0.7-1~debian.12~bookworm
SLIRP4NETNS_VERSION ?= 1.2.2

.PHONY: build
build:
	docker build -t $(DOCKER_IMAGE) \
	--build-arg=IMAGE_BASE_NAME=$(IMAGE_BASE_NAME) \
	--build-arg=IMAGE_BASE_VERSION=$(IMAGE_BASE_VERSION) \
	--build-arg=KERNEL_VERSION=$(KERNEL_VERSION) \
	--build-arg=GOLANG_VERSION=$(GOLANG_VERSION) \
	--build-arg=DOCKER_CHANNEL=$(DOCKER_CHANNEL) \
	--build-arg=DOCKER_VERSION=$(DOCKER_VERSION) \
	--build-arg=SLIRP4NETNS_VERSION=$(SLIRP4NETNS_VERSION) \
 	.

.PHONY: obfuscator
obfuscator:
	$(MAKE) -C obfuscator build

test:
	docker run -it --rm $(DOCKER_IMAGE) docker info

push:
	docker push $(DOCKER_IMAGE)

build-info:
	@echo DOCKER_TAG=$(DOCKER_TAG)
	@echo DOCKER_IMAGE=$(DOCKER_IMAGE)
	@echo
	@echo IMAGE_BASE_NAME=$(IMAGE_BASE_NAME)
	@echo IMAGE_BASE_VERSION=$(IMAGE_BASE_VERSION)
	@echo KERNEL_VERSION=$(KERNEL_VERSION)
	@echo GOLANG_VERSION=$(GOLANG_VERSION)
	@echo DOCKER_CHANNEL=$(DOCKER_CHANNEL)
	@echo DOCKER_VERSION=$(DOCKER_VERSION)
	@echo SLIRP4NETNS_VERSION=$(SLIRP4NETNS_VERSION)
